### ISSUE TITLE
css-loader v6.4 seems to have broken the hash... again

### ISSUE THREAD

**Issue by mcrawshaw** [birdofpreyru/babel-plugin-react-css-modules#18]
Key release note:
"generate more collision resistant for locals (c7db752)"

The PR:
https://github.com/webpack-contrib/css-loader/commit/c7db752fe6a9c7ff28d165fd24a37be08ef83af5

I had to revert to 6.3... Passing this packages `getLocalIdent` to css-loader did not seem to have any effect.

**Comment by birdofpreyru** [comment]
I believe v6.4.0 of this plugin resolves the problem, and is compatible with the latest **css-loader**, at least if you also use the latest Webpack, and latest versions of its plugins related to CSS loading (with which I tested the update).
