### ISSUE TITLE
Replace `lodash.foreach` to `lodash`

### ISSUE THREAD

**Issue by Semigradsky** [birdofpreyru/babel-plugin-react-css-modules#19]
See https://lodash.com/per-method-packages for reasons for change.

It is a dependency for `@dr.pogodin/postcss-modules-parser`. I tried to find `@dr.pogodin/postcss-modules-parser` repository for send PR, but it relates to https://github.com/birdofpreyru/postcss-icss, which looks like an incorrect package.

**Comment by birdofpreyru** [comment]
Done in **v6.4.1**.
