### ISSUE TITLE
Does not compile with webpack 5.58.2

### ISSUE THREAD

**Issue by ioanlucut** [birdofpreyru/babel-plugin-react-css-modules#20]
Hey!

Thanks for the plugin!
Unfortunately, there's an issue if we try to run it with the latest version of the `webpack` (5.58.2).

The error looks like this:
```
 [BABEL]: Cannot read property 'hooks' of undefined
```

Do you mind having a look?
Thanks!

**Comment by birdofpreyru** [comment]
Thanks for reporting @ioanlucut ! I'll try to fix it soon, and also to add some tests to capture similar issues in future.
