### ISSUE TITLE
It can`t work with less className "&-xxx"

### ISSUE THREAD

**Issue by ccy303** [birdofpreyru/babel-plugin-react-css-modules#22]
less file:
`.warp{
    color: #f00
    &-item:{
        color: #0f0
    }
}` 
It run with error : can`t resolve this styleName : "warp-item"
babel config
`
[
	"@dr.pogodin/react-css-modules",
	{
		// 达到类似vue的scoped效果
		filetypes: {
			".less": {
				syntax: "postcss-less",
				plugins: ["postcss-nested"],
			},
		},
		generateScopedName: "[local]-[hash:base64:10]",
		webpackHotModuleReloading: true,
	},
]
`
node version 1417.3
"less": "^4.1.2",
"less-loader": "^10.2.0",
"webpack": "^5.59.1",
"@babel/core": "^7.15.8",
"style-loader": "^3.3.1",
"@dr.pogodin/babel-plugin-react-css-modules": "^6.5.1",

**Comment by birdofpreyru** [comment]
Hey @ccy303 ,

I had a brief look at your problem. I have implemented a [test case for your scenario](https://github.com/birdofpreyru/babel-plugin-react-css-modules/tree/master/test/fixtures/react-css-modules/works%20for%20less%20stylesheet%20with%20parent%20selector%20and%20classname%20starting%20with%20dash). It works fine if I use **postcss-nested@5.0.1**, and it fails as you report if I try it with the latest **postcss-nested@5.0.6**. 

Thus, it should be the same problem noted in #5 (after [this change](https://github.com/postcss/postcss-nested/commit/ec804d17bdeaf8c239abbf123dd5303dd07237a1) **postcss-nested** is applied after **react-css-modules**, while we need it to be applied prior to it). I'll probably have a further look into this when I have time, but right now I have a bunch of higher-priority todo stuff in my schedule. If you want a quick workaround, I guess, either downgrade to **postcss-nested@5.0.1** for now, or try to investigate a fix youself.

**Comment by birdofpreyru** [comment]
I realised it is, in fact, a very simple problem to solve. I just released **v6.5.2**, which should solve the issue.

**Comment by ccy303** [comment]
> 
> 
> 我意识到这实际上是一个很容易解决的问题。 我刚刚发布了 **v6.5.2 **，应该可以解决这个问题。



> 
> 
> I realised it is, in fact, a very simple problem to solve. I just released **v6.5.2**, which should solve the issue.



> 
> 
> I realised it is, in fact, a very simple problem to solve. I just released **v6.5.2**, which should solve the issue.

thank you !
