### ISSUE TITLE
The custom path for webpack is not recognized！

### ISSUE THREAD

**Issue by moonlitusun** [birdofpreyru/babel-plugin-react-css-modules#23]
e.g: webpack resolve.alias

![image](https://user-images.githubusercontent.com/22940470/145564593-ead4f7ed-728e-4af2-b411-439865de7f04.png)

**Comment by birdofpreyru** [comment]
Hey @moonlitusun,

At the first thought, I believe this is not a problem with this plugin. Babel _per se_ does not care about aliases you configure via Webpack config. If you want to use them, you should include [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver) into your Babel config, and configure it with the same alias rules you use at the Webpack side.

**Comment by moonlitusun** [comment]
> 

Thanks for reply. I added babel-plugin-module-resolver  to run correctly
