### ISSUE TITLE
Failed tests on CRA app

### ISSUE THREAD

**Issue by Semigradsky** [birdofpreyru/babel-plugin-react-css-modules#26]
After this change: https://github.com/birdofpreyru/babel-plugin-react-css-modules/commit/8b5b79dcc13304d7890c4a294b4ada4644a54dbf I have errors when I run tests on [CRA-app](https://github.com/facebook/create-react-app)
```js
FAIL src/.../index.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    if (import.meta.webpackHot) {
               ^^^^

    SyntaxError: Cannot use 'import.meta' outside a module

```

cc @pturchik

**Comment by birdofpreyru** [comment]
Ogh...

This seems to be relevant: https://github.com/facebook/jest/issues/12183

If I got it right, the problem is not CRA, but that a module is required as CommonJS rather than ECMA, and probably in your setup there is no Babel transformation for the module in front of Jest (my Jest tests work alright everywhere after this change, but then I rely on Babel everywhere, which probably helps).

Need to think how to cover this by a tests, and workaround so that it work without extra requirements on test setup.

**Comment by Semigradsky** [comment]
> ... probably in your setup there is no Babel transformation for the module in front of Jest

Oh, it looks like I incorrectly add babel plugin to CRA. I changed adding plugin to using `addBabelPlugin` from `customize-cra` and now the tests work correctly.

https://github.com/Semigradsky/babel-plugin-react-css-modules-demo/commit/71a3818324d8b251ac667494c8675af18e4fdf97?diff=split

Thanks for your help!
