### ISSUE TITLE
TypeError: [BABEL]

### ISSUE THREAD

**Issue by kaialsh705** [birdofpreyru/babel-plugin-react-css-modules#27]
TypeError: [BABEL]: Cannot read properties of undefined (reading 'hooks') (While processing: /Users/data/react/node_modules/@dr.pogodin/babel-plugin-react-css-modules/dist/index.js)

**Comment by kaialsh705** [comment]
TypeError: [BABEL]: Cannot read properties of undefined (reading 'hooks') (While processing: /Users/data/react/node_modules/@dr.pogodin/babel-plugin-react-css-modules/dist/index.js)

**Comment by birdofpreyru** [comment]
Hey @kaialsh705, can you provide more details? I definitely don't encounter such error in my projects, nor in the current library tests. My first guess would be, you have something configured wrong, or some problem with installed babel packages.

**Comment by birdofpreyru** [comment]
Closing down as non-identified. Though, I believe the issue was that `webpack` was not installed as a dependency by issue creator, or it was outdated.
