### ISSUE TITLE
Cannot find module 'babel-plugin-react-css-modules'

### ISSUE THREAD

**Issue by silkfire** [birdofpreyru/babel-plugin-react-css-modules#3]
When building my project using your fork, I'm getting this error:

```
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-react-css-modules' from '<path-to-project-directory>'
```

I removed the original `babel-plugin-react-css-modules` npm module and replaced it with yours. Am I missing something?

**Comment by birdofpreyru** [comment]
Yes, your should update its name in your Babel config to `@dr.pogodin/babel-plugin-react-css-modules` (can be shortcut as `@dr.pogodin/react-css-modules`)

**Comment by silkfire** [comment]
@birdofpreyru Thanks, that resolved the issue. Perhaps you it'd be worth mentioning this detail in the documentation?

**Comment by birdofpreyru** [comment]
It is mentioned somewhere, but I guess indeed I should put it into the very top of README. I'll do :)

**Comment by silkfire** [comment]
YES! Programmers are lazy by nature you know :)
