### ISSUE TITLE
Cannot find module 'webpack/lib/TemplatedPathPlugin'

### ISSUE THREAD

**Issue by beilo** [birdofpreyru/babel-plugin-react-css-modules#37]
I want to use babel-plugin-react-css-modules in umi

This exception occurs when `npm run dev` is executed

```bash
Error: [BABEL]: Cannot find module 'webpack/lib/TemplatedPathPlugin'
Require stack:
- /node_modules/.pnpm/registry.npmmirror.com+@dr.pogodin+babel-plugin-react-css-modules@6.9.3/node_modules/@dr.pogodin/babel-plugin-react-css-modules/dist/getLocalIdent.js
- /node_modules/.pnpm/registry.npmmirror.com+@dr.pogodin+babel-plugin-react-css-modules@6.9.3/node_modules/@dr.pogodin/babel-plugin-react-css-modules/dist/requireCssModule.js
- /node_modules/.pnpm/registry.npmmirror.com+@dr.pogodin+babel-plugin-react-css-modules@6.9.3/node_modules/@dr.pogodin/babel-plugin-react-css-modules/dist/index.js
```

The simplest demo
1. npx create-umi@latest
2. add bottom configuration
3. npm run dev

```js
// add .umirc.ts
  mfsu: false,
  extraBabelPlugins: [
    [
      '@dr.pogodin/react-css-modules',
      {
        generateScopedName: generateScopedNameFactory(
          '[path]___[name]__[local]___[hash:base64:6]',
        ),
        webpackHotModuleReloading: true,
        handleMissingStyleName: 'warn',
        filetypes: {
          '.less': {
            syntax: 'postcss-less',
          },
          '.scss': {
            syntax: 'postcss-scss',
          },
        },
      },
    ] as any,
  ],
  autoCSSModules: false,
  cssLoader: {
    modules: {
      getLocalIdent,
      localIdentName: '[path]___[name]__[local]___[hash:base64:6]',
    },
  },
```

Thank you for your help

**Comment by birdofpreyru** [comment]
Hey @beilo , as README mentions in its [Installation] section, **Install Webpack at least as a dev dependency**. Although it is a Babel plugin, it relies on a bit of Webpack code to generate classnames that will match what Webpack generates.

[Installation]: https://github.com/birdofpreyru/babel-plugin-react-css-modules#installation

**Comment by beilo** [comment]
@birdofpreyru 
Sorry it took me so long to reply.
I was just looking at the source code.
https://github.com/umijs/umi/blob/master/packages/bundler-webpack/package.json
The version used is `"webpack": "5.75.0",`

**Comment by birdofpreyru** [comment]
@beilo well, for me the plugin works fine with Webpack v5.75.0. The next two things to check that come to my mind: (i) double-check that when you run the Babel compilation with this plugin, the webpack is really installed, in particular the files used by this plugin: `webpack/lib/TemplatedPathPlugin.js` file and `webpack/lib/util/createHash.js`; (ii) If those files are in-place, then is there anything in your project that mess with paths resolutions, and prevents imports of selected modules from Webpack? Like these:
```js
import TemplatedPathPlugin from 'webpack/lib/TemplatedPathPlugin';
import createHash from 'webpack/lib/util/createHash';
```

**Comment by beilo** [comment]
@birdofpreyru 
Thank you very much. I have submitted it to umi for their help.
