### ISSUE TITLE
exclude: 'node_modules' Not working

### ISSUE THREAD

**Issue by vttilaxuqdo0854** [birdofpreyru/babel-plugin-react-css-modules#38]
I have installed antd@4 in my project and included the following line in my `src/pages/index.tsx` file:

```jsx
import 'antd/dist/antd.css';
```

After building the project with pnpm build, I noticed that the CSS for antd in the umi.css file in the build directory includes a _hash suffix, even though I have already excluded node_modules in the build configuration. Can you please help me identify where I went wrong?

Here is a minimal example of my setup.
[umi-codemao-mobile 2.zip](https://github.com/birdofpreyru/babel-plugin-react-css-modules/files/10908726/umi-codemao-mobile.2.zip)
Steps:
1. pnpm i
2. pnpm build

**Comment by birdofpreyru** [comment]
Hi @vttilaxuqdo0854 , I had a brief look at it.

As far as the generated CSS is concerned, it is generated by `css-loader`, not by this Babel plugin. You should somehow instruct the UMI framework to not apply `css-loader` to the content of `node_modules`, and this plugin's `exclude` option is irrelevant for that.

This Babel plugin transforms CSS classnames in JS code, _i.e._ if after getting it right on the CSS side you find out that these class names are still referred with hashes on JS side, then re-open the issue. For now, I'll close it, as I believe there is no issue with `exclude` option in this plugin.

**Comment by beilo** [comment]
Sorry, I don't quite understand your meaning.

I have already turned off the `CSS module` processing in `UMI`. When I comment out those portions, the CSS in the `node_modules` folder does not have hash values. Additionally, I followed the description of `babel-plugin-react-css-modules` to handle `css-loader`.

Could you please explain to me how I should handle `css-loader`?
```
 // cssLoader: {
  //   modules: {
  //     getLocalIdent,
  //     localIdentName: cssScopeName,
  //   },
  // },

// extraBabelPlugins: [
  //   [
  //     '@dr.pogodin/react-css-modules',
  //     {
  //       generateScopedName: generateScopedNameFactory(cssScopeName),
  //       webpackHotModuleReloading: true,
  //       handleMissingStyleName: 'warn',
  //       exclude: 'node_modules',
  //       filetypes: {
  //         '.less': {
  //           syntax: 'postcss-less',
  //         },
  //         '.scss': {
  //           syntax: 'postcss-scss',
  //         },
  //       },
  //     },
  //   ] as any,
  // ],
```

**Comment by birdofpreyru** [comment]
> _Sorry, I don't quite understand your meaning._

Which part of it? `css-loader` affects generated CSS; this `@dr.pogodin/babel-plugin-react-css-modules` plugin affects generated JS, as far as I can tell, there is no problem with the plugin.

This is the first time I hear about `UMI`, and I have no idea how to configure it. With the plain Webpack (which is, I believe, hidden somewhere inside `UMI`) you can [configure](https://webpack.js.org/concepts/loaders/#configuration) two different instances of `css-loader`, one for CSS with modules, one for CSS without modules. [An example from my personal project](https://github.com/birdofpreyru/react-utils/blob/ac85cbaf352fc861883ee63cd09fca3b3b477003/config/webpack/app-base.js#L292-L326), there one set of loaders (including `css-loader`) is applied to `.scss` files to apply CSS modules to them, and bundle them in, and below just `css-loader` and `MiniCssExtractPlugin.loader` are applied to all `.css` files, just to bundle their content in, without applying CSS modules transformation. You wanna do something like that, but I have no idea, how you do it with `UMI`.

**Comment by beilo** [comment]
Thank you very much for your patient explanation. 

``` 
cssLoader: {
  modules: { 
    getLocalIdent, 
    localIdentName: cssScopeName, 
   },
}, 

```

I suspect that the problem may lie in this configuration, which may cause `css-loader` to generate hash values. I will try to seek help in `UMI iss`. 

Thank you again for your help.

**Comment by beilo** [comment]
I have resolved the issue by excluding the "node_modules" folder in the "getLocalIdent" function.
You're very welcome!
```
      localIdentName: cssScopeName,
      getLocalIdent: (context, localIdentName, localName, options) => {
        const { resourcePath } = context;
        if (/node_modules/.test(resourcePath)) {
          return localName;
        }
        return getLocalIdent(context, localIdentName, localName, options);
      },
```

**Comment by birdofpreyru** [comment]
I am glad you found a workaround that works for you. As [I said above](https://github.com/birdofpreyru/babel-plugin-react-css-modules/issues/38#issuecomment-1461687197), I'd better rely on Webpack configuration to not apply `css-loader` with modules transformation to files that do not need it.
