### ISSUE TITLE
I would like to enable the plugin to support aliases, however I have encountered difficulties. Could you assist me?

### ISSUE THREAD

**Issue by beilo** [birdofpreyru/babel-plugin-react-css-modules#40]
I have made some alterations to the code, primarily to facilitate support for alias CSS. However, I have consistently failed using Ajv. Could you assist me by providing guidance on how to add new configurations?

```
let alias: Record<string, any> = {
  src: path.resolve(__dirname, 'src'),
  '@': path.resolve(__dirname, 'src'),
};
```

https://github.com/birdofpreyru/babel-plugin-react-css-modules/compare/master...beilo:babel-plugin-react-css-modules:master

**Comment by birdofpreyru** [comment]
No, I can't provide a free support on AJV use. If you wanna do it, I guess you know where [AJV docs are](https://www.npmjs.com/package/ajv).

A free advice, however, if you use Babel and/or Webpack correctly, you don't need such custom coding to do aliasing. Babel has [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver); Webpack has [resolve.alias](https://www.npmjs.com/package/babel-plugin-module-resolver) option in its config. I am not sure they cover 100% of cases; but I definitely have some paths for SCSS files aliased in my projects, and so far it worked for me without a need for custom aliasing in this plugin.
